### ISSUE TITLE
Problems during compilation with import that have static reference in Vue Components

### ISSUE THREAD

**Issue by JeromeChevalier** [vue-styleguidist/vue-styleguidist#788] opened 2020-03-08 11:51 UTC
Hi

I have a project that contains some import done by using a static reference in my Quasar Vue JS project.

Import like this
`
import MyObject from 'src/core/component/MyObject';
`

during compilation when i run the build process of styleguidist , it's raised an error
`
Module not found: Can't resolve 'src/core/component/MyObject ...
`

It seems that it's like the compilation process it's done for each file , by taking root directory the directory where the vue file is.
Of course, if i change to a relative path it's works, but i have many occurrence to change.
Any ideas ?

Thanks in advance

**Comment by elevatebart** [comment] 2020-03-11 15:56
Hello @JeromeChevalier ,

Do you have a place I could debug it in? A code sandbox would be perfect but a small github repo would be nice too. 

If you can't, would you please tell me if the import you are doing is in an example or a component?

- [ ] what version of vue-styleguidist are you using?
- [ ] are you using the plugin for the CLI or the native package?
- [ ] do you have webpack aliases?

**Comment by elevatebart** [comment] 2020-03-19 14:23
a quick remark, if you were using a function for your webpack config, you might want to simply update vsg. as it could be a duplicate of #793

**Comment by elevatebart** [comment] 2020-03-22 21:21
Can you share your webpack.config.js or the `webpackConfig` of your `styleguide.config.js`

**Comment by elevatebart** [comment] 2020-05-09 16:33
I believe this is solved, feel free to re-open if you see it again.
thak you @JeromeChevalier

**Closed by elevatebart** 2020-05-09 16:33 UTC
