### ISSUE TITLE
Conflict: Multiple assets emit different content to the same filename index.html

### ISSUE THREAD

**Issue by uaru** [vue-styleguidist/vue-styleguidist#1482] opened 2023-02-14 06:43 UTC
I just tried to add `vue-styleguidist` to my project and failed completely:

```
Conflict: Multiple assets emit different content to the same filename index.html
```

On the second problems, I saw the comment of @elevatebart on this issue: https://github.com/vue-styleguidist/vue-styleguidist/issues/1074#issuecomment-1078640419

However, I already have this corrected version: 

```
vue-styleguidist@^4.47.0:
  version "4.56.5"
```

Here is my `styleguide.config.js`

```
const path = require('path')
module.exports = {
	// set your styleguidist configuration here
	title: 'Default Style Guide',
	components: 'src/**/[A-Z]*.vue',
	// defaultExample: true,
	sections: [
	  {
	    name: 'UI Elements',
	    components: 'src/views/ui/**/[A-Z]*.vue'
	  },
	],
	exampleMode: 'hide',
	styleguideDir: 'docs/devguide/srcdocs/vueguide/',
	webpackConfig: Object.assign({}, require('./node_modules/@vue/cli-service/webpack.config.js'),{
		resolve: {
			alias: {
			'@': path.resolve(__dirname, './src'),
			'rsg-components/Examples': path.resolve(__dirname, './node_modules/react-styleguidist/lib/client/rsg-components/Examples')
			}
		},
	})
}
```

**Comment by elevatebart** [comment] 2023-02-14 16:11
... have you thought of using the the vue cli plugin ?


https://vue-styleguidist.github.io/docs/GettingStarted.html#_1-install

```bash
vue add styleguidist
```

With the plugin, you should be able to remove the custom webpackConfig since it should be entirely built for you.

**Comment by elevatebart** [comment] 2023-02-14 16:14
should you really need to update the aliases, you can do so in [dangerouslyUpdateWebpackConfig](https://vue-styleguidist.github.io/Configuration.html#dangerouslyupdatewebpackconfig) though I don't recommend it.

**Comment by uaru** [comment] 2023-02-15 04:23
> ... have you thought of using the the vue cli plugin ?
> 
> https://vue-styleguidist.github.io/docs/GettingStarted.html#_1-install
> 
> ```shell
> vue add styleguidist
> ```
> 
> With the plugin, you should be able to remove the custom webpackConfig since it should be entirely built for you.

Thank you for your answer. 

I am completely new to the styleguidist, so `vue add styleguidist` was the first thing I did. 

I removed the webpackConfig, and it is still  the same error

<img width="676" alt="Screenshot 2023-02-15 at 13 16 37" src="https://user-images.githubusercontent.com/2102032/218929175-0a8a8dc5-fddf-45dd-b50c-8ae4f3d4f57f.png">

At least this time it did not complain about `@`, which is what it did after I run it before.

**Comment by mediafreakch** [comment] 2023-02-15 14:58
I am facing the same error. It results in the styleguide not rendering anything. 

The error seems to be related to the [`pages.filename` config option](https://cli.vuejs.org/config/#pages) in `vue.config.js`:

```js
// vue.config.js
module.exports = { 
 pages: {
    main: {
      entry: "src/main.ts",
      template: "public/index.html",
      filename: "index.html", // <--- styleguide build fails when specified, suceeds when omitted
    },
    subpage: {
      entry: "src/subpage/subpage.ts",
      template: "public/subpage.html",
      filename: "subpage.html",
    },
  },
}
```

Here's a [Stackblitz example to reproduce](https://stackblitz.com/edit/github-ahnvys-jsibyb?file=vue.config.js).

**Comment by elevatebart** [comment] 2023-02-15 15:08
@uaru do you use the `pages` option as well ?

**Comment by elevatebart** [comment] 2023-02-15 19:04
This should be fixed soon for @mediafreakch

**Comment by uaru** [comment] 2023-02-16 01:50
> @uaru do you use the `pages` option as well ?

Thank you for your reply.

No, I am not. I did not go that far.


There is one more issue. Installing styleguidist plugin adds an example file `AppButton.vue` to the `src/components`. 

With standard out-of-the-box settings, in addition to the error, it generates: 

```
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/t/Codes/field_notes/yachou-ui/src/Components/AppButton.vue` does not match the corresponding path on disk `components`.
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/t/Codes/field_notes/yachou-ui/src/Components/AppButton.vue` does not match the corresponding path on disk `components`.
Conflict: Multiple assets emit different content to the same filename index.html
```

When I add `components` to the `styleguide.config.js`,

```
components: 'src/**/[A-Z]*.vue',
```

then only multiple assets emit error is generated:

```
Conflict: Multiple assets emit different content to the same filename index.html
```

This is macOS, with a standard filesystem settings, which is supposed to be case non-sensitive. Apparently some method inside styleguidist is case sensitive. 

Edit: 

`vue.config.js` also does not seem to be anything special. 

```
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')

module.exports = {
  "transpileDependencies": [
    "vuetify", "@koumoul/vjsf"
  ],
  lintOnSave: false,
  chainWebpack: config => {
    config.module
      .rule('images')
        .use('url-loader')
          .loader('url-loader')
          .tap(options => options ? Object.assign(options, { limit: 10240 }) : {})
        .end()

    config
        .plugin('polyfills').use(NodePolyfillPlugin).end()

  },
  devServer: {
    host: '0.0.0.0',
    https: false,
    port: 8080,
    client: {
      webSocketURL: 'ws://0.0.0.0:8080/ws'
    },
    allowedHosts: ['all']
  },
}
```

**Comment by elevatebart** [comment] 2023-02-16 15:15
Hello @uaru !

Could you share a repository where I can reproduce this bug?
maybe the `devServer` is making the additional index, html file...

**Comment by uaru** [comment] 2023-02-17 01:58
Ok, I prepared a castrated version of my project, but by doing this, I discovered something, so maybe it is not needed.

Originally, I followed the instructions in here: https://vue-styleguidist.github.io/docs/GettingStarted.html#_1-install


It says basically, run 

```
vue-styleguidist build
```

Which ends in the error: 

```
Conflict: Multiple assets emit different content to the same filename index.html
```

However, when I tried to run
```
vue-cli-service styleguidist:build
```

then it ended with SUCCESS.

I discovered it, when I tried to repeat the process with my mini-project on a Ubuntu server in the cloud (I mentioned my development machine is Mac) and it complained it could not find the `vue-styleguidist` command at all.

Now why the command `vue-styleguidist build` and `vue-cli-service styleguidist:build` seem to run almost identical except for the error at the end with the first one, I have no idea. But it is at least error in documentation.

**Comment by elevatebart** [comment] 2023-02-17 02:58
I am so glad you got to enjoy the software finally. 
If you find it in you heart to add a note in the documentation about that.

Something along the lines of "if you use the vue-cli, make sure you use the vue-cli-service command"

In anyway I am glad you found a way.

**Closed as completed** 2023-03-17 17:24 UTC
Labels: bug, question
