### ISSUE TITLE
Vue 3 and "vue-template-compiler" error

### ISSUE THREAD

**Issue by marcinpalka** [vue-styleguidist/vue-styleguidist#1178] opened 2021-08-12 06:09 UTC
Hi, I installed styleguidist via Vue 3 Cli, everything went well but when I try to run it, and I keep getting this error:

```
./node_modules/vue-styleguidist/lib/client/index.js (./node_modules/vue-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/vue-styleguidist/lib/client/index.js)

Error: Cannot find module 'vue-template-compiler'
```

As far as I know "vue-template-compiler" is no longer needed in Vue 3, and it's replaced by "@vue/compiler-sfc" so I don't understand why is it needed here.

my dependencies in packge.json looks like this:

```
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.37.5",
    "sass-loader": "^10.0.0-rc.0",
    "vue-cli-plugin-styleguidist": "~4.40.0",
    "vue-styleguidist": "^4.40.0",
    "vuex": "^4.0.2"
  },
```

does anyone know how to fix it ?

**Comment by lifeart** [comment] 2021-08-12 07:44
should be fixed in https://github.com/vue-styleguidist/vue-styleguidist/pull/1002

**Comment by elevatebart** [comment] 2021-08-12 14:43
Hello @marcinpalka do you mind if I close this issue since it is a duplicate of #997.
You can subscribe to this issue instead.

Would you be interested in helping out?

**Comment by marcinpalka** [comment] 2021-08-13 08:11
Yes, of course, sorry for the duplicate and sorry but I am not feeling qualified enough to help you fix this issue. Thanks for the answer.

**Comment by elevatebart** [comment] 2021-08-13 21:25
THank you for reporting it, I hope to have time to work on it soon.

**Closed as completed** 2021-08-13 21:25 UTC
Labels: enhancement
