### ISSUE TITLE
PropOptions throws an error

### ISSUE THREAD

**Issue by hkjersem** [vue-styleguidist/vue-styleguidist#1297] opened 2022-03-22 11:58 UTC
Given this simple input:
```
<template>
....
</template>

<script>
/**
 * @typedef {{ name: string, href: string }} NavigationItem
 */

export default {
    props: {
        /**
         * @property {string} items[].name
         * @property {string} items[].href
         * @type {import('vue').PropOptions<NavigationItem[]>}
         */
        items: {
            type: Array,
            required: true,
        },
    },
};
</script>
```
I get the following error:
```
WARN  Failed getting docs for navigation Could not parse template expression:                                                                                                   
const a:import('vue').PropOptions<NavigationItem[]>
Err: Missing initializer in const declaration. (1:51)
```

**Comment by elevatebart** [comment] 2022-03-25 03:54
duplicate of #1299 fixed in upcoming version

**Closed as completed** 2022-03-25 08:40 UTC
Labels: bug
