### ISSUE TITLE
Component, Sub section not show on appendix when using sections mode

### ISSUE THREAD

**Issue by phmngocnghia** [vue-styleguidist/vue-styleguidist#199] opened 2018-09-17 05:03 UTC
My styleguide.config.js:
```js
const vueLoader = require('vue-loader');
module.exports = {
	defaultExample: true,
    version: '1.0',
    sections: [
        // Cloudjet Noti
        {
            name: 'Cloudjet notifications bell',
            description: 'Cái chuông notification được convert qua ES6 - trong #4240',
            components: './src/templates/components/clouldjet_noti/components/notification_container/notification_container.vue', // Cái này point tới component chính - container
            sections: [ // Chứa các subcomponent của component này nếu có
                {
                    name: 'Minor-components',
                    description: 'container con của cái chuuông',
                    components: './src/templates/components/clouldjet_noti/components/minor_components/**/*.vue'
                }
            ]
            // Lưu ý không được bỏ component qua xử lý store tức main.vue vào trong này                        
        }
    ]
};
```

Bugs (Image)
[Bug image](https://imgur.com/ZeiPRLE)

Reproduce reposity: later
P/S: I use vue-styleguidist in production code to demonstrate and isolated devleop our company vue component

**Comment by elevatebart** [comment] 2018-09-19 13:36
let me have a look.
Out of curiosity, why are you not using the [cli plugin](https://github.com/vue-styleguidist/vue-cli-plugin-styleguidist) ?

**Comment by PhmNgocNghia** [comment] 2018-09-20 13:18
It's legacy code base... i'm going to modernize it.

**Comment by elevatebart** [comment] 2019-06-03 20:44
how is it now ?

**Comment by elevatebart** [comment] 2019-08-06 13:05
Hello @phmngocnghia I believe this is the intended behavior of react-styleguidist
bug #492 seems to have the same problem.
If there is only one section, it disappears.

The described behavior is managed right [here](https://github.com/styleguidist/react-styleguidist/blob/d1e528fd71de2edb9850c76cd76bc268e3677398/src/client/rsg-components/TableOfContents/TableOfContents.js#L44) feel free to add an issue.

**Comment by elevatebart** [comment] 2019-08-20 22:43
it is now fixed and delivered

**Closed by elevatebart** 2019-08-20 22:43 UTC

**Comment by elevatebart** [comment] 2019-08-20 22:44
[V-3.22.0](https://github.com/vue-styleguidist/vue-styleguidist/releases/tag/v3.22.0)
