### ISSUE TITLE
[Feature Request] Ability to use vue/html for docs instead of markdown

### ISSUE THREAD

**Issue by phmngocnghia** [vue-styleguidist/vue-styleguidist#198] opened 2018-09-17 04:15 UTC
In markdown i can use ```jsx or ```vue to embed jsx and vue some time i want all document it inside vue instance instead write markdown or \<docs>

Also markdown has cons with some IDE:
- No syntaxhighlight
- No autocompleteion

**Comment by elevatebart** [comment] 2018-12-03 01:34
Hello @PhmNgocNghia,

What syntax would you have in mind? Some kind of include? Or writing the entire documenation like in [storybook](https://github.com/storybooks/storybook) ?

**Comment by PhmNgocNghia** [comment] 2018-12-03 13:11
Maybe allow to extract example from .vue, or .html file would be great.  Since they are native file extension, most ide will support above features such as: syntanx highlight, autocompletion.

**Comment by elevatebart** [comment] 2019-02-18 12:32
You should try using JavaScript as a markdown language highlight. Works nice for templates.

**Comment by elevatebart** [comment] 2019-08-20 22:49
You can now import examples from external files into your markdown which will bring back some of the autocompletion and syntax highlighting. 
Check out [the docs](https://vue-styleguidist.github.io/docs/Documenting.html#importing-examples)

The other part which is authoring content as HTML is a duplicate of #304. Please follow on this issue.

**Closed by elevatebart** 2019-08-20 22:49 UTC
Labels: enhancement
